FROM openjdk:11 AS BUILD_IMAGE
COPY . /usr/src/ilovemovies
WORKDIR /usr/src/ilovemovies

COPY build.gradle gradlew gradlew.bat .
COPY gradle ./gradle
# download dependencies
RUN ./gradlew build -x :bootRepackage -x test --continue
COPY . .
RUN ./gradlew build

FROM openjdk:11-jre
WORKDIR /root/
COPY --from=BUILD_IMAGE /root/dev/myapp/build/libs/myapp.jar .
EXPOSE 8080
CMD ["java","-jar","myapp.jar"]