configuration:
  db:
    host: localhost
    port: 5432
    user: ilovemovies
    password: ilovemovies
spring:
  datasource:
    url: jdbc:postgresql://${configuration.db.host}:${configuration.db.port}/ilovemovies
    username: ${configuration.db.user}
    password: ${configuration.db.password}
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: postgresql
