ALTER TABLE movie ALTER COLUMN version TYPE INTEGER;
ALTER TABLE director ADD COLUMN version INTEGER;
ALTER TABLE actor ADD COLUMN version INTEGER;
ALTER TABLE roles ALTER COLUMN version TYPE INTEGER;
